feat(ci-cd):dummy testing for staging

diff --git a/.github/workflows/ci-cd-frontend.yml b/.github/workflows/ci-cd-frontend.yml
--- a/.github/workflows/ci-cd-frontend.yml
+++ b/.github/workflows/ci-cd-frontend.yml
@@ -31,7 +31,7 @@ jobs:
         run: npm test
 
       - name: Build React App
-        run: npm run build --verbose  # Tambahkan --verbose untuk debugging
+        run: npm run build --verbose # Tambahkan --verbose untuk debugging
 
       - name: Debug Build Output
         run: ls -la build/ || echo "Build folder not found"
@@ -72,23 +72,25 @@ jobs:
       - name: Deploy to Staging
         if: github.ref == 'refs/heads/staging'
         run: |
-          ssh -p 2223 govy6997@go-village.id << 'EOF'
+          ssh -p 2223 -v govy6997@go-village.id "echo Test connection" || echo "SSH connection failed"
+          ssh -p 2223 -o ConnectTimeout=30 -o ConnectionAttempts=3 govy6997@go-village.id << 'EOF'
             if [ ! -d "/home/govy6997/public_html/staging/example.go-village.id" ]; then
               mkdir -p /home/govy6997/public_html/staging/example.go-village.id
             fi
             rm -rf /home/govy6997/public_html/staging/example.go-village.id/*
             exit
           EOF
-          scp -r -P 2223 build/* govy6997@go-village.id:/home/govy6997/public_html/staging/example.go-village.id/
+          rsync -avz --progress -e "ssh -p 2223 -o ConnectTimeout=30 -o ConnectionAttempts=3" build/ govy6997@go-village.id:/home/govy6997/public_html/staging/example.go-village.id/
 
       - name: Deploy to Production
         if: github.ref == 'refs/heads/main'
         run: |
-          ssh -p 2223 govy6997@go-village.id << 'EOF'
+          ssh -p 2223 -v govy6997@go-village.id "echo Test connection" || echo "SSH connection failed"
+          ssh -p 2223 -o ConnectTimeout=30 -o ConnectionAttempts=3 govy6997@go-village.id << 'EOF'
             if [ ! -d "/home/govy6997/public_html/production/sukma.go-village.id" ]; then
               mkdir -p /home/govy6997/public_html/production/sukma.go-village.id
             fi
             rm -rf /home/govy6997/public_html/production/sukma.go-village.id/*
             exit
           EOF
-          scp -r -P 2223 build/* govy6997@go-village.id:/home/govy6997/public_html/production/sukma.go-village.id/
+          rsync -avz --progress -e "ssh -p 2223 -o ConnectTimeout=30 -o ConnectionAttempts=3" build/ govy6997@go-village.id:/home/govy6997/public_html/production/sukma.go-village.id/
